# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rebar_inference_pb2 as rebar__inference__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rebar_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RebarInferenceStub:
    """*
    钢筋直径测量设备 — gRPC 服务定义

    本文件严格遵循 AGENTS.md §5.5 冻结版本，禁止随意修改字段。

    服务拓扑（双节点各监听 50051，独立 channel）：
    - 节点 A 的 server: 提供 Infer RPC（节点 B 调用 → B→A 方向）
    - 节点 B 的 server: 提供 Heartbeat + Shutdown RPC（节点 A 调用 → A→B 方向）
    - 节点 A 同时作为 gRPC 客户端，周期调用节点 B 的 Heartbeat 并在退出时调用 Shutdown

    ============================================================
    服务定义
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/rebar.inference.RebarInference/Infer',
                request_serializer=rebar__inference__pb2.InferRequest.SerializeToString,
                response_deserializer=rebar__inference__pb2.InferResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/rebar.inference.RebarInference/Heartbeat',
                request_serializer=rebar__inference__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=rebar__inference__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/rebar.inference.RebarInference/Shutdown',
                request_serializer=rebar__inference__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=rebar__inference__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class RebarInferenceServicer:
    """*
    钢筋直径测量设备 — gRPC 服务定义

    本文件严格遵循 AGENTS.md §5.5 冻结版本，禁止随意修改字段。

    服务拓扑（双节点各监听 50051，独立 channel）：
    - 节点 A 的 server: 提供 Infer RPC（节点 B 调用 → B→A 方向）
    - 节点 B 的 server: 提供 Heartbeat + Shutdown RPC（节点 A 调用 → A→B 方向）
    - 节点 A 同时作为 gRPC 客户端，周期调用节点 B 的 Heartbeat 并在退出时调用 Shutdown

    ============================================================
    服务定义
    ============================================================

    """

    def Infer(self, request, context):
        """推理请求（B→A）：节点 B 发送 JPEG 帧，节点 A 返回 PNG 类别掩码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """心跳保活（A→B）：节点 A 周期性推送存活性探测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """退出通知（A→B）：节点 A 退出前一次性通知节点 B（best-effort）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RebarInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=rebar__inference__pb2.InferRequest.FromString,
                    response_serializer=rebar__inference__pb2.InferResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=rebar__inference__pb2.HeartbeatRequest.FromString,
                    response_serializer=rebar__inference__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=rebar__inference__pb2.ShutdownRequest.FromString,
                    response_serializer=rebar__inference__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rebar.inference.RebarInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rebar.inference.RebarInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RebarInference:
    """*
    钢筋直径测量设备 — gRPC 服务定义

    本文件严格遵循 AGENTS.md §5.5 冻结版本，禁止随意修改字段。

    服务拓扑（双节点各监听 50051，独立 channel）：
    - 节点 A 的 server: 提供 Infer RPC（节点 B 调用 → B→A 方向）
    - 节点 B 的 server: 提供 Heartbeat + Shutdown RPC（节点 A 调用 → A→B 方向）
    - 节点 A 同时作为 gRPC 客户端，周期调用节点 B 的 Heartbeat 并在退出时调用 Shutdown

    ============================================================
    服务定义
    ============================================================

    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rebar.inference.RebarInference/Infer',
            rebar__inference__pb2.InferRequest.SerializeToString,
            rebar__inference__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rebar.inference.RebarInference/Heartbeat',
            rebar__inference__pb2.HeartbeatRequest.SerializeToString,
            rebar__inference__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rebar.inference.RebarInference/Shutdown',
            rebar__inference__pb2.ShutdownRequest.SerializeToString,
            rebar__inference__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
