# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/rebar_inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/rebar_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/rebar_inference.proto\x12\x0frebar.inference\"a\n\x0cInferRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\r\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\x1a\n\x12\x63\x61mera_distance_mm\x18\x04 \x01(\x01\"\x97\x01\n\rInferResponse\x12\x12\n\nlabel_mask\x18\x01 \x01(\x0c\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\r\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\r\n\x05width\x18\x04 \x01(\r\x12\x0e\n\x06height\x18\x05 \x01(\r\x12+\n\x06status\x18\x06 \x01(\x0e\x32\x1b.rebar.inference.NodeStatus\"\x9b\x01\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12+\n\x06status\x18\x03 \x01(\x0e\x32\x1b.rebar.inference.NodeStatus\x12\x13\n\x0binfer_count\x18\x04 \x01(\r\x12\x1e\n\x16last_infer_duration_ms\x18\x05 \x01(\r\"B\n\x11HeartbeatResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x1b\n\x13server_timestamp_ms\x18\x02 \x01(\x03\"u\n\x0fShutdownRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12+\n\x06status\x18\x03 \x01(\x0e\x32\x1b.rebar.inference.NodeStatus\x12\x0e\n\x06reason\x18\x04 \x01(\t\"E\n\x10ShutdownResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x1b\n\x13server_timestamp_ms\x18\x02 \x01(\x03*p\n\nNodeStatus\x12\x17\n\x13NODE_STATUS_UNKNOWN\x10\x00\x12\x14\n\x10NODE_STATUS_IDLE\x10\x01\x12\x14\n\x10NODE_STATUS_BUSY\x10\x02\x12\x1d\n\x19NODE_STATUS_SHUTTING_DOWN\x10\x03\x32\xfd\x01\n\x0eRebarInference\x12\x46\n\x05Infer\x12\x1d.rebar.inference.InferRequest\x1a\x1e.rebar.inference.InferResponse\x12R\n\tHeartbeat\x12!.rebar.inference.HeartbeatRequest\x1a\".rebar.inference.HeartbeatResponse\x12O\n\x08Shutdown\x12 .rebar.inference.ShutdownRequest\x1a!.rebar.inference.ShutdownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.rebar_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODESTATUS']._serialized_start=717
  _globals['_NODESTATUS']._serialized_end=829
  _globals['_INFERREQUEST']._serialized_start=48
  _globals['_INFERREQUEST']._serialized_end=145
  _globals['_INFERRESPONSE']._serialized_start=148
  _globals['_INFERRESPONSE']._serialized_end=299
  _globals['_HEARTBEATREQUEST']._serialized_start=302
  _globals['_HEARTBEATREQUEST']._serialized_end=457
  _globals['_HEARTBEATRESPONSE']._serialized_start=459
  _globals['_HEARTBEATRESPONSE']._serialized_end=525
  _globals['_SHUTDOWNREQUEST']._serialized_start=527
  _globals['_SHUTDOWNREQUEST']._serialized_end=644
  _globals['_SHUTDOWNRESPONSE']._serialized_start=646
  _globals['_SHUTDOWNRESPONSE']._serialized_end=715
  _globals['_REBARINFERENCE']._serialized_start=832
  _globals['_REBARINFERENCE']._serialized_end=1085
# @@protoc_insertion_point(module_scope)
